import os
import time
import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException, Response
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

# 1. Initialize FastAPI app
app = FastAPI(
    title="Titanic Survival Prediction API",
    description="Production-ready inference service with Prometheus monitoring.",
    version="1.0.0"
)

# 2. Prometheus Metrics definitions
REQUEST_COUNT = Counter(
    "api_request_count_total", 
    "Total HTTP requests received", 
    ["method", "endpoint", "status"]
)
REQUEST_LATENCY = Histogram(
    "api_request_latency_seconds", 
    "Histogram of request latencies in seconds", 
    ["endpoint"]
)
PREDICTION_COUNT = Counter(
    "model_prediction_count_total", 
    "Total predictions generated by the model", 
    ["prediction"]
)

# 3. Path to trained model
MODEL_PATH = os.path.join("models", "model.joblib")
if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(f"Trained model not found at {MODEL_PATH}!")

model = joblib.load(MODEL_PATH)


# 4. Pydantic Schemas
class PassengerInput(BaseModel):
    Pclass: int = Field(..., ge=1, le=3, description="Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd)", example=3)
    Sex: str = Field(..., description="Gender: 'male' or 'female'", example="female")
    Age: float = Field(..., ge=0, le=120, description="Age in years", example=22.0)
    SibSp: int = Field(..., ge=0, description="Number of siblings/spouses aboard", example=1)
    Parch: int = Field(..., ge=0, description="Number of parents/children aboard", example=0)
    Fare: float = Field(..., ge=0.0, description="Passenger fare", example=7.25)
    Embarked: str = Field(..., description="Port of Embarkation: 'C', 'Q', or 'S'", example="S")


class PredictionResponse(BaseModel):
    survived: bool
    survival_probability: float


# 5. Prometheus Scrape Endpoint
@app.get("/metrics")
def get_metrics():
    """Exposes Prometheus application metrics."""
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.get("/")
def health_check():
    return {"status": "healthy", "service": "titanic-survival-prediction"}


@app.get("/drift", response_class=FileResponse)
def get_drift_report():
    """Serves the interactive Evidently AI drift report HTML."""
    report_path = os.path.join("monitoring", "drift_report.html")
    if not os.path.exists(report_path):
        raise HTTPException(
            status_code=404, 
            detail="Drift report not found. Run drift detection first."
        )
    return FileResponse(report_path, media_type="text/html")


@app.post("/predict", response_model=PredictionResponse)
def predict(passenger: PassengerInput):
    start_time = time.time()
    try:
        input_data = pd.DataFrame([{
            "Pclass": passenger.Pclass,
            "Age": passenger.Age,
            "SibSp": passenger.SibSp,
            "Parch": passenger.Parch,
            "Fare": passenger.Fare,
            "Sex_male": 1 if passenger.Sex.lower() == "male" else 0,
            "Embarked_Q": 1 if passenger.Embarked.upper() == "Q" else 0,
            "Embarked_S": 1 if passenger.Embarked.upper() == "S" else 0,
        }])

        prediction = model.predict(input_data)[0]
        probability = model.predict_proba(input_data)[0][1]

        # Record metrics
        PREDICTION_COUNT.labels(prediction=str(int(prediction))).inc()
        REQUEST_COUNT.labels(method="POST", endpoint="/predict", status="200").inc()
        REQUEST_LATENCY.labels(endpoint="/predict").observe(time.time() - start_time)

        return PredictionResponse(
            survived=bool(prediction == 1),
            survival_probability=round(float(probability), 4)
        )

    except Exception as e:
        REQUEST_COUNT.labels(method="POST", endpoint="/predict", status="500").inc()
        raise HTTPException(status_code=500, detail=str(e))
